# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4a536873385beddc392acf8e5f7c8103121740e652aff647c813cbae5605266d25383df2e2f275c92e027dbfd2d4de763825ae688c013526d777a3524fc08f7

test:
  secret_key_base: a00f4eaea670ef100b0226f96fadd4abda3c3a66d88abbd7ad22828d666c0befcba038d540f73258fadcb4e7d382f3103cd5d920a1c7f5e56269acb9d7540813

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
